name: Auto Merge PR

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.draft == false }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        cd backend
        pytest .

    - name: Enable auto-merge
      uses: peter-evans/enable-pull-request-automerge@v3
      with:
        token: ${{ secrets.GH_PAT }}
        merge-method: squash
        pull-request-number: ${{ github.event.pull_request.number }}
